### PR TITLE
Fix technology table

### LINKED ISSUE #71: Restyling technology table
Restyling techonology table as per @solaris007 comments

### PR DESCRIPTION
**Pull request by cuzuco2**
Please review):

Fix #71

Test URLs:
- Before: https://main--elco-aerotop-sg--hlxsites.hlx.page/de/
- After: https://fix-technology-table--elco-aerotop-sg--hlxsites.hlx.page/de/

### CODE REVIEW

File: blocks/technology-table/technology-table.js [hunk 1]
```diff
@@ -1,25 +1,26 @@
 function buildTechnologyTable(block) {
```
Comment (solaris007) [inline blocks/technology-table/technology-table.js:1]: @cuzuco2 the piece that is missing is that you can source an array from the node list and therefore use all the nice array functions. i'd re-write the function like this:

```
function buildTechnologyTable(block) {
  const rows = block.querySelectorAll('.technology-table > div');
  rows.forEach((cell, i) => {
    Array.from(cell.children)
      .forEach((child) => {
        if (i === 0) {
          const titleText = child.textContent;
          const title = document.createElement('h1');

          child.textContent = '';
          title.textContent = titleText;
          title.style.fontSize = 'var(--heading-font-size-l)';
          title.style.textAlign = 'left';

          child.appendChild(title);
          child.classList.add('techno-table-title');
        } else if (i === 1) {
          child.classList.add('techno-table-image');
        } else if (i === 2) {
          child.classList.add('techno-table-description');
        }
      });
  });
}
```

Comment (cuzuco2) [reply blocks/technology-table/technology-table.js:1]: Ah ok that was it, thanks

**Review by solaris007 — DISMISSED** [review]

**Comment by cuzuco2** [comment]
I just discovered that the text is not aligned correctly and should be aligned left.
I will do that and resubmit the PR

**Review by solaris007 — APPROVED** [review]
